-- Insert 50 sample vinyl records
INSERT INTO records (artist, album_artist, album, year, genre, record_label, format, condition, album_artwork) VALUES
('The Beatles', 'The Beatles', 'Abbey Road', 1969, ARRAY['Rock', 'Pop'], 'Apple Records', 'LP', 'Mint', 'abbey_road.jpg'),
('Pink Floyd', 'Pink Floyd', 'The Dark Side of the Moon', 1973, ARRAY['Progressive Rock'], 'Harvest', 'LP', 'Near Mint', 'dark_side.jpg'),
('Michael Jackson', 'Michael Jackson', 'Thriller', 1982, ARRAY['Pop', 'R&B'], 'Epic Records', 'LP', 'Mint', 'thriller.jpg'),
('Led Zeppelin', 'Led Zeppelin', 'Led Zeppelin IV', 1971, ARRAY['Hard Rock'], 'Atlantic Records', 'LP', 'Very Good', 'zeppelin_iv.jpg'),
('Fleetwood Mac', 'Fleetwood Mac', 'Rumours', 1977, ARRAY['Pop Rock', 'Soft Rock'], 'Warner Bros', 'LP', 'Mint', 'rumours.jpg'),
('Queen', 'Queen', 'A Night at the Opera', 1975, ARRAY['Rock'], 'EMI', 'LP', 'Near Mint', 'night_opera.jpg'),
('The Rolling Stones', 'The Rolling Stones', 'Exile on Main St.', 1972, ARRAY['Rock', 'Blues'], 'Rolling Stones Records', 'LP', 'Good', 'exile.jpg'),
('David Bowie', 'David Bowie', 'Ziggy Stardust', 1972, ARRAY['Glam Rock'], 'RCA', 'LP', 'Mint', 'ziggy.jpg'),
('Nirvana', 'Nirvana', 'Nevermind', 1991, ARRAY['Grunge', 'Alternative Rock'], 'DGC Records', 'LP', 'Mint', 'nevermind.jpg'),
('Radiohead', 'Radiohead', 'OK Computer', 1997, ARRAY['Alternative Rock', 'Art Rock'], 'Parlophone', 'LP', 'Near Mint', 'ok_computer.jpg'),
('Prince', 'Prince', 'Purple Rain', 1984, ARRAY['Pop', 'Rock', 'R&B'], 'Warner Bros', 'LP', 'Mint', 'purple_rain.jpg'),
('Miles Davis', 'Miles Davis', 'Kind of Blue', 1959, ARRAY['Jazz', 'Modal Jazz'], 'Columbia', 'LP', 'Very Good Plus', 'kind_of_blue.jpg'),
('Jimi Hendrix', 'Jimi Hendrix', 'Are You Experienced', 1967, ARRAY['Psychedelic Rock'], 'Track Records', 'LP', 'Good Plus', 'are_you_experienced.jpg'),
('Bob Dylan', 'Bob Dylan', 'Highway 61 Revisited', 1965, ARRAY['Folk Rock'], 'Columbia', 'LP', 'Near Mint', 'highway_61.jpg'),
('Stevie Wonder', 'Stevie Wonder', 'Songs in the Key of Life', 1976, ARRAY['Soul', 'Funk'], 'Motown', 'LP', 'Mint', 'songs_key_life.jpg'),
('AC/DC', 'AC/DC', 'Back in Black', 1980, ARRAY['Hard Rock'], 'Albert Productions', 'LP', 'Very Good', 'back_in_black.jpg'),
('Metallica', 'Metallica', 'Master of Puppets', 1986, ARRAY['Thrash Metal'], 'Elektra', 'LP', 'Near Mint', 'master_puppets.jpg'),
('U2', 'U2', 'The Joshua Tree', 1987, ARRAY['Rock'], 'Island Records', 'LP', 'Mint', 'joshua_tree.jpg'),
('Guns N'' Roses', 'Guns N'' Roses', 'Appetite for Destruction', 1987, ARRAY['Hard Rock'], 'Geffen', 'LP', 'Good', 'appetite.jpg'),
('Beastie Boys', 'Beastie Boys', 'Licensed to Ill', 1986, ARRAY['Hip Hop'], 'Def Jam', 'LP', 'Very Good Plus', 'licensed_ill.jpg'),
('A Tribe Called Quest', 'A Tribe Called Quest', 'The Low End Theory', 1991, ARRAY['Hip Hop', 'Jazz Rap'], 'Jive Records', 'LP', 'Mint', 'low_end_theory.jpg'),
('Kendrick Lamar', 'Kendrick Lamar', 'To Pimp a Butterfly', 2015, ARRAY['Hip Hop', 'Jazz'], 'Aftermath', 'LP', 'Mint Sealed', 'pimp_butterfly.jpg'),
('Daft Punk', 'Daft Punk', 'Discovery', 2001, ARRAY['Electronic', 'House'], 'Virgin Records', 'LP', 'Near Mint', 'discovery.jpg'),
('Massive Attack', 'Massive Attack', 'Mezzanine', 1998, ARRAY['Trip Hop'], 'Circa', 'LP', 'Very Good', 'mezzanine.jpg'),
('Portishead', 'Portishead', 'Dummy', 1994, ARRAY['Trip Hop'], 'Go! Beat', 'LP', 'Mint', 'dummy.jpg'),
('OutKast', 'OutKast', 'Aquemini', 1998, ARRAY['Hip Hop'], 'LaFace', 'LP', 'Near Mint', 'aquemini.jpg'),
('Nas', 'Nas', 'Illmatic', 1994, ARRAY['Hip Hop'], 'Columbia', 'LP', 'Mint', 'illmatic.jpg'),
('Wu-Tang Clan', 'Wu-Tang Clan', 'Enter the Wu-Tang', 1993, ARRAY['Hip Hop'], 'Loud Records', 'LP', 'Good Plus', 'enter_wu_tang.jpg'),
('The Notorious B.I.G.', 'The Notorious B.I.G.', 'Ready to Die', 1994, ARRAY['Hip Hop'], 'Bad Boy', 'LP', 'Near Mint', 'ready_to_die.jpg'),
('Jay-Z', 'Jay-Z', 'Reasonable Doubt', 1996, ARRAY['Hip Hop'], 'Roc-A-Fella', 'LP', 'Mint', 'reasonable_doubt.jpg'),
('Dr. Dre', 'Dr. Dre', 'The Chronic', 1992, ARRAY['G-Funk', 'Hip Hop'], 'Death Row', 'LP', 'Very Good Plus', 'chronic.jpg'),
('Snoop Dogg', 'Snoop Dogg', 'Doggystyle', 1993, ARRAY['G-Funk', 'Hip Hop'], 'Death Row', 'LP', 'Near Mint', 'doggystyle.jpg'),
('Tom Petty', 'Tom Petty and the Heartbreakers', 'Damn the Torpedoes', 1979, ARRAY['Rock', 'Heartland Rock'], 'MCA', 'LP', 'Good', 'damn_torpedoes.jpg'),
('Bruce Springsteen', 'Bruce Springsteen', 'Born to Run', 1975, ARRAY['Rock'], 'Columbia', 'LP', 'Very Good', 'born_to_run.jpg'),
('Neil Young', 'Neil Young', 'Harvest', 1972, ARRAY['Folk Rock'], 'Reprise', 'LP', 'Mint', 'harvest.jpg'),
('Eagles', 'Eagles', 'Hotel California', 1976, ARRAY['Rock'], 'Asylum', 'LP', 'Near Mint', 'hotel_california.jpg'),
('Talking Heads', 'Talking Heads', 'Remain in Light', 1980, ARRAY['New Wave', 'Post-Punk'], 'Sire', 'LP', 'Mint', 'remain_light.jpg'),
('The Clash', 'The Clash', 'London Calling', 1979, ARRAY['Punk Rock', 'New Wave'], 'CBS', 'LP', 'Good Plus', 'london_calling.jpg'),
('Joy Division', 'Joy Division', 'Unknown Pleasures', 1979, ARRAY['Post-Punk'], 'Factory', 'LP', 'Very Good', 'unknown_pleasures.jpg'),
('New Order', 'New Order', 'Power, Corruption & Lies', 1983, ARRAY['New Wave', 'Synth-Pop'], 'Factory', 'LP', 'Mint', 'pctl.jpg'),
('Depeche Mode', 'Depeche Mode', 'Violator', 1990, ARRAY['Synth-Pop'], 'Mute', 'LP', 'Near Mint', 'violator.jpg'),
('The Cure', 'The Cure', 'Disintegration', 1989, ARRAY['Gothic Rock', 'Post-Punk'], 'Fiction', 'LP', 'Very Good Plus', 'disintegration.jpg'),
('Sonic Youth', 'Sonic Youth', 'Daydream Nation', 1988, ARRAY['Noise Rock', 'Alternative'], 'Enigma Records', 'LP', 'Good', 'daydream_nation.jpg'),
('Pixies', 'Pixies', 'Doolittle', 1989, ARRAY['Alternative Rock'], '4AD', 'LP', 'Mint', 'doolittle.jpg'),
('The Smiths', 'The Smiths', 'The Queen Is Dead', 1986, ARRAY['Indie Rock'], 'Rough Trade', 'LP', 'Very Good', 'queen_is_dead.jpg'),
('Cocteau Twins', 'Cocteau Twins', 'Heaven or Las Vegas', 1990, ARRAY['Dream Pop', 'Ethereal Wave'], '4AD', 'LP', 'Near Mint', 'heaven_las_vegas.jpg'),
('My Bloody Valentine', 'My Bloody Valentine', 'Loveless', 1991, ARRAY['Shoegaze', 'Noise Pop'], 'Creation', 'LP', 'Mint Sealed', 'loveless.jpg'),
('Aphex Twin', 'Aphex Twin', 'Selected Ambient Works 85-92', 1992, ARRAY['Ambient', 'Techno'], 'Apollo', 'LP', 'Very Good', 'saw.jpg'),
('Boards of Canada', 'Boards of Canada', 'Music Has the Right to Children', 1998, ARRAY['Ambient', 'IDM'], 'Warp', 'LP', 'Mint', 'boc_mhra.jpg'),
('Gorillaz', 'Gorillaz', 'Demon Days', 2005, ARRAY['Alternative Rock', 'Hip Hop'], 'Parlophone', 'LP', 'Near Mint', 'demon_days.jpg'),
('Arctic Monkeys', 'Arctic Monkeys', 'Whatever People Say I Am', 2006, ARRAY['Indie Rock', 'Post-Punk'], 'Domino', 'LP', 'Mint', 'arctic_debut.jpg');
